### PR TITLE
#358 - added pack / unpack scripts to simplify editing inline scripts

### PR DESCRIPTION
**Pull request by mikeclayton**
Added some utility scripts to unpack inline ScriptBody, PreDeploy, Deploy and PostDeploy scripts out of step template *.json files into separate files for easier  script development. Also contains a packer to put them back into the *.json step template again afterwards (which could be used in a CI process if desired).

Usage:
'''
C:\src\Library\step-templates>powershell . .\_unpack.ps1
C:\src\Library\step-templates>powershell . .\_pack.ps1
```

Most of the current step templates round-trip pretty much byte-for-byte, with a few whitespace inconsistencies and "\u0027 <->apostrophe" swaps that might need cleaning up.

Not sure if this is the best location to commit the scripts, so move them around if there's a better place for them.

### CODE REVIEW

**Comment by dragon788** [comment]
I like it. This will be really helpful for those who are still using older versions of Octopus and can't take advantage of the "script in a nupkg" from 3.3.x.

**Comment by alfhenrik** [comment]
Hey @dragon788,

To me it feels like this would be better located under the `tools` folder as we do some pre-processing of everything under the `step-templates` folder. 

If you could also update the `README` with a section on how to get started with this handy tool that be great and I would happily merge this PR.

Thanks,
Henrik

**Comment by espoelstra** [comment]
@alfhenrik that does make sense if you are doing extra processing under step-templates. @mikeclayton Think you can add another commit to change the path to go under tools, maybe in its own subfolder?

**Comment by mikeclayton** [comment]
PR updated as requested.

I've put some comments in issue #358, but it probably makes more sense to move the discussion to this PR, so I'll repost-below.

**Comment by mikeclayton** [comment]
Would there any appetite for storing the scripts separately from the templates in this repo, and "packing" them during the CI process?

Some advantages would be:

* A lot easier to contribute fixes to templates contributors wouldn't have to care about extracting scripts from the step templates.

* The history for scripts would be a lot more readable as separate files rather than encoded json on a single line in the step templates.

* It also opens the door to testing the PowerShell scripts is isolation with something like Pester. 

I can raise a separate issue for this if it's worth discussing.

**Comment by dragon788** [comment]
I just tried this and it looks like the relative path was coded assuming that the unpack/pack were living in the step-templates folder. Probably need to tweak this to handle living in tools beside the step-templates.

**Comment by mikeclayton** [comment]
Ah, sorry. Failed at the first hurdle :-(

I'll take a look tonight.

**Comment by mikeclayton** [comment]
@dragon788 - I've fixed the relative file path boo-boo in my previous commit (I'd copied the script templates up a folder so the path was accidentally valid on my machine!).

I've also added a -Force switch to the unpack script to control overwriting existing files (default is to *not* overwrite, but happy to invert that if preferred).

**Comment by dragon788** [comment]
Awesome! I may have to add a pull request eventually to add the -Force passthrough logic to the Converter script, but calling the _pack and _unpack scripts directly may be easier for those doing full on automation to avoid yet another layer of abstraction.

**Pull request merged**
