### PR TITLE
Allow multiple auth methods. different file name to package. Executes…

### PR DESCRIPTION
**Pull request by DannyArr**
… as PS job.
---

### Step template checklist

- [x] `Id` should be a **GUID** that is not `00000000-0000-0000-0000-000000000000`
  - **NOTE** If you are modifying an existing step template, please make sure that you **do not** modify the `Id` property *(updating the `Id` will break the Library sync functionality in Octopus)*. 
- [x] `Version` should be incremented, otherwise the integration with Octopus won't update the step template correctly
- [x] Parameter names should not start with `$`
- [ ] **Step template parameter names (the ones declared in the JSON, not the script body) should be prefixed with a namespace so that they are less likely to clash with other user-defined variables in Octopus** (see [this issue](https://github.com/OctopusDeploy/Issues/issues/2126)). For example, use an abbreviated name of the step template or the category of the step template).
- [x] `LastModifiedBy` field must be present, and (_optionally_) updated with the correct author
- [ ] If a new `Category` has been created:
   - [ ] An image with the name `{categoryname}.png` must be present under the `step-templates/logos` folder
   - [ ] The `switch` in the `humanize` function in [`gulpfile.babel.js`](https://github.com/OctopusDeploy/Library/blob/master/gulpfile.babel.js#L92) must have a `case` statement corresponding to it

### CODE REVIEW

**Comment by DannyArr** [comment]
- Allows for additional authentication methods such as Azure AD. Before was just Integrated or SQL auth.
- Allows package name to differ from dacpac file name. Extra param DACPACFileName
- Now runs under a PowerShell job, to avoid timeout situations where the deployment completed, but the Octopus job still shows as in progress.

**New required params:**
- DACPAC File Name (Breaking change)
- SQL Server Authentication Method 
- Command Timeout

Removed param for "Use Integrated Security". This is to allow for the different authentication methods, not just SQL Server auth and Windows AD, giving more options when deploying to Azure.

**Comment by mreeder** [comment]
Hi @DannyArr, Thanks for the contribution! I think the majority of this functionality is covered with this similar step template: https://library.octopus.com/step-templates/ae9d0024-a5aa-4aa8-95a9-cba53c291054/actiontemplate-sql-deploy-dacpac-with-aad-auth-support. Please check that one and let me know if you feel different or if some of these changes belong there.

As an aside, when making changes, it's best to make them from the file from master versus exporting the template and updating the file with that version as all of the ID's change which can cause issues with people using the existing version.

**Comment by twerthi** [comment]
@DannyArr, does the template that @mreeder linked provide similar functionality?  Does it work for you?

**Comment by harrisonmeister** [comment]
This PR hasn't had any activity since Dec 2021, so I will close this one off. Please reach out if you'd like us to re-consider the PR, keeping in mind our comments about the [alternative template](https://library.octopus.com/step-templates/ae9d0024-a5aa-4aa8-95a9-cba53c291054/actiontemplate-sql-deploy-dacpac-with-aad-auth-support) available.

**Pull request closed without merging**
