### PR TITLE
Add configurable security support for HTTPS requests to "HTTP - Test URL"

### PR DESCRIPTION
**Pull request by Craigology**
### Summary

**Added support to be able to specify the security protocol for HTTPS requests to sites that mandate the minimum permitted TLS version.**

### Rationale

With reference to [this blog bost](https://blogs.msdn.microsoft.com/appserviceteam/2018/04/17/app-service-and-functions-hosted-apps-can-now-update-tls-versions/) dated 17th April 2018, Microsoft Azure App Service now supports the ability to configure the minimum required TLS protocol for HTTPS connections, and as stated, _"From June 30th, 2018, all newly created App Service apps will automatically have TLS 1.2 selected as the default configuration."_

Evidently, the industry will be increasingly moving this way.

###  Implementation Notes

Powershell can set the .NET Security Protocol setting on a per-session basis. See [here](https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel).

I have added an optional drop-down to the list of parameters which allows a selection from the supported enum values in the `System.Net.SecurityProtocolType` enumeration, which is then applied before the request invocation is performed.

This has been tested satisfactorily against an Azure app service HTTPS site requiring TLS 1.2.

### CODE REVIEW

**Comment by alfhenrik** [comment]
Hi @Craigology, thank you for your PR! 

I have been away on holidays so I have not had time to review it just yet, but it's on the todo list and I will hopefully 🤞 get to it today.

My apologies for the delay in getting the review done!

Cheers,
Henrik

**Comment by Craigology** [comment]
Thanks Henrik, no worries at all. 👍 

Cheers,
Craig.

**Comment by Craigology** [comment]
Thanks @alfhenrik. 👍

**Pull request merged**
