### PR TITLE
Update Code to Account for Regex in Channel Rules

### PR DESCRIPTION
**Pull request by aburke-incomm**
### Step template guidelines

* Is the template a minor variation on an existing one? If so, please consider improving the existing template if possible.
* Is the name of the template consistent with the examples already in the library, in style ("Noun - Verb"), layout and casing?
* Are all parameters in the template consistent with the examples here, including help text documented with Markdown?
* Is the description of the template complete, correct Markdown?
* Is the `.json` filename consistent with the name of the template?
* Do scripts in the template validate required arguments and fail by returning a non-zero exit code when things go wrong?
* Do scripts in the template produce worthwhile status messages as they execute?
* Are you happy to contribute your template under the terms of the [license](https://github.com/OctopusDeploy/Library/blob/master/LICENSE)? If you produced the template while working for your employer please obtain written permission from them before submitting it here.
* Are the default values of parameters validly applicable in other user's environments? Don't use the default values as examples if the user will have to change them
* For how to deal with parameters and testing take a look at the article [Making great Octopus PowerShell step templates](https://www.daniellittle.xyz/making-great-octopus-powershell-step-templates/)
* For another example of how to test your step template script body before submitting a PR take a look at this [gist](https://gist.github.com/JCapriotti/45639e06ba777ee974b1)

_Before submitting your PR, please delete everything above the line below._

---

### Step template checklist

- [ ] `Id` should be a **GUID** that is not `00000000-0000-0000-0000-000000000000`
  - **NOTE** If you are modifying an existing step template, please make sure that you **do not** modify the `Id` property *(updating the `Id` will break the Library sync functionality in Octopus)*. 
- [ ] `Version` should be incremented, otherwise the integration with Octopus won't update the step template correctly
- [ ] Parameter names should not start with `$`
- [ ] **Step template parameter names (the ones declared in the JSON, not the script body) should be prefixed with a namespace so that they are less likely to clash with other user-defined variables in Octopus** (see [this issue](https://github.com/OctopusDeploy/Issues/issues/2126)). For example, use an abbreviated name of the step template or the category of the step template).
- [ ] `LastModifiedBy` field must be present, and (_optionally_) updated with the correct author
- [ ] If a new `Category` has been created:
   - [ ] An image with the name `{categoryname}.png` must be present under the `step-templates/logos` folder
   - [ ] The `switch` in the `humanize` function in [`gulpfile.babel.js`](https://github.com/OctopusDeploy/Library/blob/master/gulpfile.babel.js#L92) must have a `case` statement corresponding to it

Fixes # . _If there is an open issue that this PR fixes add it here, otherwise just remove this line_

### CODE REVIEW

**Comment by DevOpsDerek** [comment]
Hi @aburke-incomm, 

Could I get you to sign the CLA? We need it to publish the step template. 

Additionally, please update: 

- Lastmodifiedby
- Octopus version exported from

**Comment by aburke-incomm** [comment]
Thanks Derek,

I have signed the CLA.

I modified the version directly in GitHub. I performed no export, so my change was based on v18. Is that okay?

I am running an On-Prem version of 2019.10.5. Is that what would you like for the export version?

Thanks,

AARON BURKE
Software Engineer II
InComm InCentives

**Comment by twerthi** [comment]
We prefer the export version be the version it was exported from, so that is fine.  It looks like there was a changelog for this template, would you mind adding an entry to keep it consistent?

**Comment by aburke-incomm** [comment]
Added the Change log and updated script to reflect the requested values. I also updated the script on my end as the community based version was not reachable at the time when we imported the original script.

This have been hugely helpful in our environment, and I wanted to give back when I could.

Thanks,

AARON BURKE
Software Engineer II
InComm InCentives

**Comment by twerthi** [comment]
Thanks @aburke-incomm !

**Pull request merged**
