### PR TITLE
New template PagerDuty-OpenMaintenanceWindow

### PR DESCRIPTION
**Pull request by nskerl**
Open a new maintenance window for the specified services.

No new incidents will be created for a service that is currently in
maintenance.

### CODE REVIEW

**Comment by alfhenrik** [comment]
Thanks @nskerl for your contribution.

I've pushed your step template to production now.

**Comment by nskerl** [comment]
Thanks Henrik.  Im working on the sister template to close the PagerDuty alert. Wondering if you had any ideas how best to pass an output variable from the Open step down to the Close? Im not sure how to refer to the open's step name given that users of this template might name it whatever they want. 

Should I assume a user can provide the step name to me via an input variable? This feels fragile.
Also, a user might use the Open template more than once in a project; that further complicates the resolution of the WindowId returned in the PagerDuty response object.

Any examples you can point to are much appreciated!

For example (pseudocode):

```
# Step1 Open Maintenance Window 
$Response = PagerDuty-OpenMaintenanceWindow...
Set-OctopusVariable -name "PagerDutyMaintenanceWindowId" -value $Response.WindowId
```

```
...
main deploy steps occur
...
```

```
# Step99 Close Maintenance Window
$IdToClose = #{Octopus.Action[$UserProvidesStepNameHere].Output.PagerDutyMaintenanceWindowId}
CallToPagerDutyAPI ($IdToClose)
```

**Comment by alfhenrik** [comment]
Hi Nathan,

You can add it as a parameter to your step template and make it a `Previous deployment step name` control type, this will then allow you to reference any output variables created in that step.

Hope that helps!
Thanks
Henrik

**Comment by nskerl** [comment]
dude, that is awesome.

**Pull request merged**
