### PR TITLE
Updated the default value to serverUri rather than baseUrl

### PR DESCRIPTION
**Pull request by kundanramisetti**
This change will use the new system variable (Octopus.Web.ServerUri) introduced in 2019.04 to build the `$Chain_BaseUrl`. Currently this step template uses the `Octopus.Web.BaseUrl` system variable which resolves to a short domain name and is failing to resolve.

# Step template checklist

- [x] `Id` should be a **GUID** that is not `00000000-0000-0000-0000-000000000000`
  - **NOTE** If you are modifying an existing step template, please make sure that you **do not** modify the `Id` property *(updating the `Id` will break the Library sync functionality in Octopus)*. 
- [x] `Version` should be incremented, otherwise the integration with Octopus won't update the step template correctly
- [ ] Parameter names should not start with `$`
- [ ] **To minimize the risk of step template parameters clashing with other variables in a project that uses the step template, ensure that you prefix your parameter names (e.g. an abbreviated name for the step template or the category of the step template**
- [x] `LastModifiedBy` field must be present, and (_optionally_) updated with the correct author
- [ ] If a new `Category` has been created:
   - [ ] An image with the name `{categoryname}.png` must be present under the `step-templates/logos` folder
   - [ ] The `switch` in the `humanize` function in [`gulpfile.babel.js`](https://github.com/OctopusDeploy/Library/blob/master/gulpfile.babel.js#L92) must have a `case` statement corresponding to it

### CODE REVIEW

**Comment by matt-richardson** [comment]
@kundanramisetti - thanks for your PR!
Unfortunately, this will break for customers who are on versions older than `2019.4.0`. Can you make it use the new variable if it exists and is not null or empty, otherwise, use the old variable?

**Comment by kundanramisetti** [comment]
Sure, will do @matt-richardson

**Comment by kundanramisetti** [comment]
Added the backward compatibility support @matt-richardson. I am not a powershell guy so please let me know if I need to follow any particular conventions. Thanks

**Comment by gupta-kartik** [comment]
@kundanramisetti thanks so much for your PR! While we test your changes, can you please sign the CLA above? We won't be able to merge it till the CLA is signed.

**Pull request merged**
