### PR TITLE
[Fix] Set Feed Ids to null to prevent validation error in non-default spaces

### PR DESCRIPTION
**Pull request by paulegradie**
Fixes: https://github.com/OctopusDeploy/Issues/issues/6733

Summary: When a community step template defines a package feed id, if a use tries to copy this template in a non-default space, a validation error will most likely be produced since it is unlikely that the feed Id will exist in another users space. This includes using the default space default feed Id when in a non-default space.

Setting the package feed Id is not necessary, so this PR sets the package feed Ids in all templates where a variable is not used to null.

### CODE REVIEW

**Comment by paulegradie** [comment]
[FeedId is not cleared from step templates](https://trello.com/c/81Ks429s/4115-feedid-is-not-cleared-from-step-templates)

**Review by harrisonmeister — CHANGES_REQUESTED** [review]
@paulegradie - in order for octopus instances to know there is a change, the version on each of these templates need there version property incremented (usually by 1 😁)

**Comment by paulegradie** [comment]
Ah good to know. I think there should also be a test for the feed Id so I'll add that in as well.

**Comment by paulegradie** [comment]
Hey @harrisonmeister - I've added the test in and have incremented the updated templates.

**Comment by harrisonmeister** [comment]
> Hey @harrisonmeister - I've added the test in and have incremented the updated templates.

Thanks @paulegradie - we'll take a look in our day today :+1:

**Review by harrisonmeister — APPROVED** [review]
LGTM

**Pull request merged**
