### PR TITLE
AlwaysLatest

### PR DESCRIPTION
**Pull request by REOScotte**
# Background

Add a DeploymentMode option for AlwaysLatest. This will find the latest release and always deploy it, even if it has already been deployed. The can be thought of as a combination of the existing options of Promote and Redploy.

# Results

If a user selects "AlwaysLatest" as the DeploymentMode, the latest available release will be always be deployed, even if it needs to be redeployed.

## After

# Pre-requisites

- [X] `Id` should be a **GUID** that is not `00000000-0000-0000-0000-000000000000`
  - **NOTE** If you are modifying an existing step template, please make sure that you **do not** modify the `Id` property *(updating the `Id` will break the Library sync functionality in Octopus)*. 
- [X] `Version` should be incremented, otherwise the integration with Octopus won't update the step template correctly
- [X] Parameter names should not start with `$`
- [X] **Step template parameter names (the ones declared in the JSON, not the script body) should be prefixed with a namespace so that they are less likely to clash with other user-defined variables in Octopus** (see [this issue](https://github.com/OctopusDeploy/Issues/issues/2126)). For example, use an abbreviated name of the step template or the category of the step template).
- [X] `LastModifiedBy` field must be present, and (_optionally_) updated with the correct author
- [X] If a new `Category` has been created:
   - [ ] An image with the name `{categoryname}.png` must be present under the `step-templates/logos` folder
   - [ ] The `switch` in the `humanize` function in [`gulpfile.babel.js`](https://github.com/OctopusDeploy/Library/blob/master/gulpfile.babel.js#L92) must have a `case` statement corresponding to it

### CODE REVIEW

**Comment by twerthi** [comment]
Greetings!  The changes requested seem to merge existing functionality of `Deployment Mode` combined with `Force Redeployment`.

image

Is there a different use case where these would not satisfy?

**Comment by REOScotte** [comment]
Looks like the Force Redeployment parameter got dropped in the “Re-working how the release has already been deployed function works” commit from Dec 16, 2021.

**Comment by twerthi** [comment]
There is one change I'd like to see and then it should be able to be merged.  The updated functions are relying on the PowerShell default value functionality if the argument is omitted,
```
function Get-ReleaseCanBeDeployedToTargetEnvironment
{
    param (
        $release,        
        $defaultUrl,
        $spaceId,
        $octopusApiKey,
        $sourceDestinationEnvironmentInfo,
        $tenantToDeploy,
        $isPromotionMode,
        $isAlwaysLatestMode = $script:isAlwaysLatestMode
    )
```

Please update the function calls to include the new environment for consistency and ease of following

```
$releaseCanBeDeployed = Get-ReleaseCanBeDeployedToTargetEnvironment -defaultUrl $defaultUrl -release $releaseInformation -spaceId $spaceId -octopusApiKey $octopusApiKey -sourceDestinationEnvironmentInfo $sourceDestinationEnvironmentInfo -tenantToDeploy $tenantToDeploy -isPromotionMode $isPromotionMode
```

**Comment by REOScotte** [comment]
:) That was intention to show a better (imho) way of sharing variables across a set of related functions. The functions in that script are all intended to share a common scope. But since functions create their own scope, the script is relegated to passing large chunks of the variables around. Using default values that point to the script-scoped version can eliminate that and make the code easier to follow. Maybe that effort could be part of a larger refactoring effort. I would be happy to put that together.

In any case, I've updated the changes as requested.

**Review by twerthi — APPROVED** [review]
LGTM

**Pull request merged**
