### PR TITLE
bugfix: opslevel deploy event needs deferred package reference

### PR DESCRIPTION
**Pull request by rocktavious**
Hey @BobJWalker  - Thanks for the help - hopefully this is what you meant.

### CODE REVIEW

**Review by ddorosz — APPROVED** [review]

**Review by BobJWalker — APPROVED** [review]
Yes, that package reference should do the trick.  Extract set to true.  Without a CLI and account to download and test, everything looks like it should work.

**Review by BobJWalker — CHANGES_REQUESTED** [review]
Ooooops, sorry.  Could you update the version numbers?

**Comment by rocktavious** [comment]
@BobJWalker oh ya right the version number.  Ok bumped

**Comment by BobJWalker** [comment]
Sorry, for the library, we only support integers.  I should have specified, bump the version to 2.

**Comment by rocktavious** [comment]
@BobJWalker ahh - ok thanks bumped to 2

**Review by BobJWalker — APPROVED** [review]
LGTM

**Pull request merged**
