### PR TITLE
Step template to deploy SSRS reports

### PR DESCRIPTION
**Pull request by twerthi**
Uploads Sql Server Reporting Services reports from a NuGet package to
SSRS instance.

### CODE REVIEW

**Comment by alfhenrik** [comment]
LGTM, just one minor thing, could you please rename the file to `ssrs-deploy-from-package.json` to keep in line with our naming scheme of `{service}{action}`

Thanks!

**Comment by twerthi** [comment]
Certainly!  My apologies, I’m not familiar with LGTM, what does that mean?

**Comment by twerthi** [comment]
The rename has been completed.

**Comment by alfhenrik** [comment]
LGTM = Looks Good To Me :smile:

**Comment by twerthi** [comment]
Oh!  Okay ☺  New to GitHub, not used to the lingo just yet.  PR threw me for a loop too :P

**Comment by vanessalove** [comment]
@twerthi 
Hi Shawn,

We have had a support request come in about this PR. Not having SSRS installed anywhere we are unable to assist. Is it something you can help or provide guidance with? http://help.octopusdeploy.com/discussions/problems/35429 

Vanessa

**Comment by twerthi** [comment]
Hi Vanessa!  I’m trying to take a look, I created an account, but it would appear that it doesn’t have access to that particular discussion.

**Comment by vanessalove** [comment]
Hi Shawn, 
I have added you as a participant. Thanks for your help!

**Comment by twerthi** [comment]
I’m in!  Thanks!  I will see if I can help, initial look shows what looks to be a false positive when the user says it was successful.  Overloaded at work, but I will try to make sure to respond as quickly as I can.

**Comment by vanessalove** [comment]
We really appreciate your help thanks!

**Pull request merged**
