### PR TITLE
Add Snowchange - Deploy Scripts template for new Snowflake Category

### PR DESCRIPTION
**Pull request by apfinger**
---

### Step template checklist

- [x] `Id` should be a **GUID** that is not `00000000-0000-0000-0000-000000000000`
  - **NOTE** If you are modifying an existing step template, please make sure that you **do not** modify the `Id` property *(updating the `Id` will break the Library sync functionality in Octopus)*. 
- [x] `Version` should be incremented, otherwise the integration with Octopus won't update the step template correctly
- [x] Parameter names should not start with `$`
- [x] **Step template parameter names (the ones declared in the JSON, not the script body) should be prefixed with a namespace so that they are less likely to clash with other user-defined variables in Octopus** (see [this issue](https://github.com/OctopusDeploy/Issues/issues/2126)). For example, use an abbreviated name of the step template or the category of the step template).
- [x] `LastModifiedBy` field must be present, and (_optionally_) updated with the correct author
- [x] If a new `Category` has been created:
   - [x] An image with the name `{categoryname}.png` must be present under the `step-templates/logos` folder
   - [x] The `switch` in the `humanize` function in [`gulpfile.babel.js`](https://github.com/OctopusDeploy/Library/blob/master/gulpfile.babel.js#L92) must have a `case` statement corresponding to it

Fixes # . _If there is an open issue that this PR fixes add it here, otherwise just remove this line_

### CODE REVIEW

**Comment by JChatmasOctopus** [comment]
@apfinger Please sign the CLA found here: https://cla-assistant.io/OctopusDeploy/Library?pullRequest=976
Thank you!

**Comment by apfinger** [comment]
When I go there the site says I already signed it.


-------- Original message --------

**Comment by harrisonmeister** [comment]
> When I go there the site says I already signed it.

Hi @apfinger - The CLA plugin is saying the following:

> Andrew Finger seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.

Can you double-check the email address used for the commits on this PR?

**Comment by apfinger** [comment]
Sorry about that - still learning how to properly navigate GitHub and account management.  Everything should be set, now.

**Comment by apfinger** [comment]
@JChatmasOctopus I'm not sure if I can remove the waiting-for-contributor label, but I think this is now ready.  Closing the PR wasn't intentional earlier - that was the only option when I previously commented (Comment was grayed out).

**Comment by harrisonmeister** [comment]
Hey @apfinger,

I've removed the label and we'll take a look either today or early tomorrow for you!

Thanks!

**Pull request merged**
