### PR TITLE
Added "Conceal Source Maps" step template

### PR DESCRIPTION
**Pull request by uoziod**
### Step template checklist

- [x] `Id` should be a **GUID** that is not `00000000-0000-0000-0000-000000000000`
  - **NOTE** If you are modifying an existing step template, please make sure that you **do not** modify the `Id` property *(updating the `Id` will break the Library sync functionality in Octopus)*. 
- [x] `Version` should be incremented, otherwise the integration with Octopus won't update the step template correctly
- [x] Parameter names should not start with `$`
- [x] **To minimize the risk of step template parameters clashing with other variables in a project that uses the step template, ensure that you prefix your parameter names (e.g. an abbreviated name for the step template or the category of the step template**
- [x] `LastModifiedBy` field must be present, and (_optionally_) updated with the correct author
- [x] If a new `Category` has been created:
   - [x] An image with the name `{categoryname}.png` must be present under the `step-templates/logos` folder
   - [x] The `switch` in the `humanize` function in [`gulpfile.babel.js`](https://github.com/OctopusDeploy/Library/blob/master/gulpfile.babel.js#L92) must have a `case` statement corresponding to it

### CODE REVIEW

**Comment by uoziod** [comment]
Not sure why build if failed after 2nd commit. Edited version works perfectly on my instance.

**Comment by alfhenrik** [comment]
Hi @uoziod,

The build is failing due to `Expected template "Conceal Source Maps" to have a valid LastModifiedBy field, but it was undefined.`. So if you add the `LastModifiedBy` field to the JSON just above the `$Meta` field the build should go green again and I will review your PR.

Thank you,
Henrik

**Comment by alfhenrik** [comment]
Hi @uoziod,

I saw you updated the parameter for the step name, but I have a question, where is that variable (`WebDeployPackageStepName`) coming from? It's not in the list of configurable parameters on the step template and it is not a built-in Octopus variable that is available by default.

Cheers,
Henrik

**Comment by uoziod** [comment]
Indeed, @alfhenrik, that was rudimentary code from another template. It's refactored now.
Thanks for finding!

**Comment by hnrkndrssn** [comment]
Hi @uoziod,

Apologies for the delay in reviewing your latest changes.

Now that you've removed the package step name variable from the code this step template will only work if there is a single package step in the deployment process, *or* only after the first package step has run. So if you have multiple package steps and you want to run this step template, the deployment will fail as successive runs of this step will fail with `Multiple package steps have run; please specify a single step`.

I'd suggest adding back the `WebDeployPackageStepName` variable and adding it as a configurable parameter on the step. This way you can run this step after multiple package steps in a  deployment.

Cheers,
Henrik

**Comment by uoziod** [comment]
Will you suggest to use `WebDeployPackageStepName` variable name or `CsmWebDeployPackageStepName`?

**Comment by hnrkndrssn** [comment]
I'd suggest you go with `CsmWebDeployPackageStepName`.

**Comment by hnrkndrssn** [comment]
As I haven't heard anything since my last comment, I will close this PR. If you still would like for us to reconsider it, please open a new PR and we'll review.

**Pull request closed without merging**
