### PR TITLE
ClickOnce related step templates

### PR DESCRIPTION
**Pull request by Kemyke**
Contains three scripts which are useful if you want to manipulate clickonce manifest and application files during a deployment. There is an exsisting ClickOnceRe-Sign template but it has some hardcoded path and tightly couples all individual steps. I created separate steps for each action and add extra parameters to be more flexible.

### CODE REVIEW

**Comment by alfhenrik** [comment]
Hi @Kemyke thank you very much for your contribution!

I have merged your step templates and progressed them through to production.

Thank you and best regards,
Henrik

**Comment by Kemyke** [comment]
I hope these scripts will be useful for other developers.
Can i ask you what is the reason that some of the scripts does not contain the name of the exporter on the library.octopusdeploy.com site? It is only says "exported by". :)

Thanks!

**Comment by alfhenrik** [comment]
It's due to a missing field `LastModifiedBy` in the exported JSON file, we've made changes to how audit related information is stored and as part of this this field is not being exported. I'll fix up those three scripts manually for you.

**Comment by Kemyke** [comment]
Thank you!

**Comment by alfhenrik** [comment]
Your step templates have been updated now.

**Pull request merged**
