### PR TITLE
Add capturing liquibase command output

### PR DESCRIPTION
**Pull request by olsh**
Add capturing the output of the Liquibase command to `LiquibaseCommandOutput` variable.
It may be useful when you want to use conditions in other steps.

Our use case is to run `liquibase status` command first, analyze the output, and the skip manual intervention step (and other Liquibase steps) if there are no changes.

### CODE REVIEW

**Comment by harrisonmeister** [comment]
Hey @olsh 

Thanks for the contribution to the Liquibase template! 

Aside from the change itself, I only have one minor comment to help users. 

Would you mind updating the description to make a note that an output variable is created (and provide the name of it). For example, something like this:

> Once the Liquibase commands have executed, the output is stored in an Octopus [output variable](https://octopus.com/docs/projects/variables/output-variables) called `LiquibaseCommandOutput` for use in subsequent Octopus deployment or runbook steps.

**Review by harrisonmeister — CHANGES_REQUESTED** [review]
Please add comment to description making note of the output variable that is created :)

**Comment by olsh** [comment]
> Please add comment to description making note of the output variable that is created :)

Hi @harrisonmeister
Done, thank you!

**Review by harrisonmeister — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
