### PR TITLE
Shared DataSet support

### PR DESCRIPTION
**Pull request by twerthi**
Added Shared DataSet support and ability to specify different credentials when running template

### CODE REVIEW

**Comment by twerthi** [comment]
GRR!  Please only take the Update ssrs-deploy-from-package.json, that's the only change I have done.

**Comment by twerthi** [comment]
Thanks!  When will this be available on the Library?

Shawn Sesna
Data Team supervisor/Configuration Manager
Department of Early Learning
P.O. Box 40970 | 505 Union Ave. S.E., Suite 300
Shawn.sesna@del.wa.gov<mailto:Shawn.sesna@del.wa.gov> | Office: 360.407.1972 | Cell: 360.628.7202
www.del.wa.gov<http://www.del.wa.gov>
Kids' Potential, Our Purpose

**Comment by alfhenrik** [comment]
Hi @twerthi, 

Ironically enough, we're currently having a few deployment issues with the library site, we're working on getting this sorted as quickly as we can and once we can deploy again I will push it to Production.

Thank you and kind regards,
Henrik

**Comment by twerthi** [comment]
Thanks!  If I may ask to hold off for now?  Manoj is reporting that he’s encountering an error.  I’ve been unable to reproduce and have asked for his RDL to try to resolve https://library.octopusdeploy.com/#!/step-template/actiontemplate-deploy-ssrs-reports-from-a-package


Shawn Sesna
Data Team supervisor/Configuration Manager
Department of Early Learning
P.O. Box 40970 | 505 Union Ave. S.E., Suite 300
Shawn.sesna@del.wa.gov<mailto:Shawn.sesna@del.wa.gov> | Office: 360.407.1972 | Cell: 360.628.7202
www.del.wa.gov<http://www.del.wa.gov>
Kids' Potential, Our Purpose

**Comment by twerthi** [comment]
I’ve been unable to reproduce the error(s) that Manoj was reporting.  Using an example Manoj provided, the step template works as designed and doesn’t produce any of the errors Manoj reported.

Shawn Sesna
Data Team supervisor/Configuration Manager
Department of Early Learning
P.O. Box 40970 | 505 Union Ave. S.E., Suite 300
Shawn.sesna@del.wa.gov<mailto:Shawn.sesna@del.wa.gov> | Office: 360.407.1972 | Cell: 360.628.7202
www.del.wa.gov<http://www.del.wa.gov>
Kids' Potential, Our Purpose


From: Sesna, Shawn (DEL)
Sent: Wednesday, November 04, 2015 4:03 PM
To: 'OctopusDeploy/Library' <reply@reply.github.com>; OctopusDeploy/Library <Library@noreply.github.com>
Subject: RE: [Library] Shared DataSet support (#237)

Thanks!  If I may ask to hold off for now?  Manoj is reporting that he’s encountering an error.  I’ve been unable to reproduce and have asked for his RDL to try to resolve https://library.octopusdeploy.com/#!/step-template/actiontemplate-deploy-ssrs-reports-from-a-package


Shawn Sesna
Data Team supervisor/Configuration Manager
Department of Early Learning
P.O. Box 40970 | 505 Union Ave. S.E., Suite 300
Shawn.sesna@del.wa.gov<mailto:Shawn.sesna@del.wa.gov> | Office: 360.407.1972 | Cell: 360.628.7202
www.del.wa.gov<http://www.del.wa.gov>
Kids' Potential, Our Purpose

**Comment by twerthi** [comment]
There’s a syntax error, please do not publish.  I will make another pull request once I have fixed it.

Shawn Sesna
Data Team supervisor/Configuration Manager
Department of Early Learning
P.O. Box 40970 | 505 Union Ave. S.E., Suite 300
Shawn.sesna@del.wa.gov<mailto:Shawn.sesna@del.wa.gov> | Office: 360.407.1972 | Cell: 360.628.7202
www.del.wa.gov<http://www.del.wa.gov>
Kids' Potential, Our Purpose

**Pull request merged**
