### PR TITLE
Create Azure Manage WebJob

### PR DESCRIPTION
**Pull request by sharmaharry**
# Background

The PR is to merge a new template for managing Azure web job

# Results
This template uses azure tools rather than octopus inbuilt tools and users do not get an error

### CODE REVIEW

**Comment by hnrkndrssn** [comment]
Hi @sharmaharry, thank you for your contribution. 

It seems we already have a [step template](https://library.octopus.com/step-templates/ac7868f9-dc5c-42b8-ab8c-0c1e801f6957/actiontemplate-azure-administer-webjob) for managing Azure web jobs. The only difference I can see between this template and yours is the type of the step (`Octopus.Script` vs `Octopus.AzurePowerShell`) and that you can select an Azure account as part of your template but it's not used as part of the script and the interaction with the Kudu API is still done via username/password specified on the step.

Could you please clarify what the difference between these two steps are, and if there is an issue with the existing step that you are hoping to fix by the addition of this new step?

Thank you,
Henrik

**Comment by sharmaharry** [comment]
> Hi @sharmaharry, thank you for your contribution.
> 
> It seems we already have a [step template](https://library.octopus.com/step-templates/ac7868f9-dc5c-42b8-ab8c-0c1e801f6957/actiontemplate-azure-administer-webjob) for managing Azure web jobs. The only difference I can see between this template and yours is the type of the step (`Octopus.Script` vs `Octopus.AzurePowerShell`) and that you can select an Azure account as part of your template but it's not used as part of the script and the interaction with the Kudu API is still done via username/password specified on the step.
> 
> Could you please clarify what the difference between these two steps are, and if there is an issue with the existing step that you are hoping to fix by the addition of this new step?
> 
> Thank you, Henrik


Hi 

This template has a little more update than the other one as this will allow users to select between Azure preinstalled tools or Azure tools bundled with Octopus. 

Using an old template we get a warning message  for using octopus pre-installed azure tools and further octopus will not be supporting those in future.

**Comment by sharmaharry** [comment]
@hnrkndrssn do you need any more input on this before you approve the PR ?

**Comment by ann-mwangi** [comment]
Here is [the issue](https://github.com/OctopusDeploy/Library/issues/1516) associated with this PR.

**Comment by sharmaharry** [comment]
> Here is [the issue](https://github.com/OctopusDeploy/Library/issues/1516) associated with this PR.

anything else pending ?

**Comment by domenicsim1** [comment]
> > Here is [the issue](https://github.com/OctopusDeploy/Library/issues/1516) associated with this PR.
> 
> anything else pending ?

Hi @sharmaharry,
Looking over the PR, and the name of JSON file does not match the conventions that we follow and is missing an extinction. Could you please rename the file to `azure-manage-webjob.json`.

**Review by domenicsim1 — APPROVED** [review]

**Pull request merged**
