### PR TITLE
enabled template to add/update lambda environment variable(s) and updates lambda configuration.

### PR DESCRIPTION
**Pull request by jasmin-mistry**
This AWS create lambda step template will now be able to;
- add/update the lambda environment variable(s),
- when updating it will now update the lambda configuration along with the lambda function code.

### CODE REVIEW

**Comment by jasmin-mistry** [comment]
Sorry guys, can we cancel this pull request as I realized that we can add more configurations for lambda functions like VPC, Subnet and Security Group. So I'm working on adding that and we can update all at once.

**Comment by alfhenrik** [comment]
Instead of closing this PR, feel free to add the additional functionality to it instead.

**Comment by jasmin-mistry** [comment]
Hi @alfhenrik, 

I have updated the template, could you please review the changes and do the needful.

Thanks,
Jasmin

**Pull request merged**
