### PR TITLE
Added the ability to set permissions for multiple folders

### PR DESCRIPTION
**Pull request by HumanPrinter**

### CODE REVIEW

**Comment by alfhenrik** [comment]
Hey @HumanPrinter, 

Thanks for your continued contributions to the Octopus Deploy community library!

It looks like the email attached to the commit isn't associated with your GitHub account (hence the CLA is showing as not signed), could you have a look and make sure that it is? If it is, then let me know as we have had other instances where the `CLAassistant` has had this issue.

Thanks,
Henrik

**Comment by HumanPrinter** [comment]
Hello @alfhenrik 

I just went through the steps to (re-)commit to the CLA. I didn't have this problems during previous pull requests, but perhaps this is a new feature that was just enabled? However, the thread-history shows that all contributors have signed the CLA at the start of the pull request.

Regards,
Oscar

**Comment by alfhenrik** [comment]
Hey @HumanPrinter,

Yep now all is looking good, previously it was showing as `pending`, this is a feature we have recently enabled due to the nature of OSS projects :)

Thanks!

**Pull request merged**
