### PR TITLE
Added aws install windows tentacle

### PR DESCRIPTION
**Pull request by xtreampb**
### Step template checklist

- [ ] `Id` should be a **GUID** that is not `00000000-0000-0000-0000-000000000000`
  - **NOTE** If you are modifying an existing step template, please make sure that you **do not** modify the `Id` property *(updating the `Id` will break the Library sync functionality in Octopus)*. 
- [ ] `Version` should be incremented, otherwise the integration with Octopus won't update the step template correctly
- [ ] Parameter names should not start with `$`
- [ ] **Step template parameter names (the ones declared in the JSON, not the script body) should be prefixed with a namespace so that they are less likely to clash with other user-defined variables in Octopus** (see [this issue](https://github.com/OctopusDeploy/Issues/issues/2126)). For example, use an abbreviated name of the step template or the category of the step template).
- [ ] `LastModifiedBy` field must be present, and (_optionally_) updated with the correct author

### CODE REVIEW

**Review by twerthi — DISMISSED** [review]
I should have put this on the other one, but I missed it.  For both the Linux and Windows version, can you make the port configurable?  In most cases, users use 10933, but not always.  Also, both of these templates specifically add Listening tentacles (unless I missed something), so we should probably update the title to reflect that.

**Comment by xtreampb** [comment]
@harrisonmeister added port number here

**Comment by harrisonmeister** [comment]
@xtreampb - I've updated the title and description to reflect the listening communication mode for the tentacle.

**Review by harrisonmeister — APPROVED** [review]
Reverted the title description after seeing the parameter for tentacle type :+1:

**Pull request merged**
