### PR TITLE
Add latest SQL Release feature.

### PR DESCRIPTION
**Pull request by PeterGerrard**
- added `SQLReleaseTemporaryDatabaseServer` parameter to Deploy from Package, and Create Database Release steps.
- updated the minimum required version of SQL Release
- Added the creation date of the step templates to their descriptions.

### CODE REVIEW

**Comment by tugberkugurlu** [comment]
@alfhenrik, @DamianMac hey :smile: Is it possible to get this in?

**Comment by alfhenrik** [comment]
Done! Will be pushed live soon.

**Comment by alfhenrik** [comment]
This is now live

**Comment by tugberkugurlu** [comment]
@alfhenrik :heart: thx!

**Pull request merged**
