### PR TITLE
Variables - Substitute in Json file

### PR DESCRIPTION
**Pull request by kazizahir**
Use this step template after the Deploy API step template to
substitute variables in a target json file like appsettings.json
with Octopus scoped variables. Currently supported data types
are string, boolean, interger, decimal and non-empty string arrays and can replace 
these types inside nested types as well as long as you name them like 
prop:subprop:subsubprop (like AppMetrics:GlobalTags:env)
this should be enough for most of the needs for files like
appsettings.json

### Step template guidelines

* Is the template a minor variation on an existing one? If so, please consider improving the existing template if possible.
* Is the name of the template consistent with the examples already in the library, in style ("Noun - Verb"), layout and casing?
* Are all parameters in the template consistent with the examples here, including help text documented with Markdown?
* Is the description of the template complete, correct Markdown?
* Is the `.json` filename consistent with the name of the template?
* Do scripts in the template validate required arguments and fail by returning a non-zero exit code when things go wrong?
* Do scripts in the template produce worthwhile status messages as they execute?
* Are you happy to contribute your template under the terms of the [license](https://github.com/OctopusDeploy/Library/blob/master/LICENSE)? If you produced the template while working for your employer please obtain written permission from them before submitting it here.
* Are the default values of parameters validly applicable in other user's environments? Don't use the default values as examples if the user will have to change them
* For how to deal with parameters and testing take a look at the article [Making great Octopus PowerShell step templates](http://www.lavinski.me/making-great-octopus-powershell-step-templates/)
* For another example of how to test your step template script body before submitting a PR take a look at this [gist](https://gist.github.com/JCapriotti/45639e06ba777ee974b1)

### CODE REVIEW

**Comment by kazizahir** [comment]
I have already signed the Contributor License Agreement but it is still saying not signed...

**Comment by kazizahir** [comment]
Hi @alfhenrik ...hope you are doing great :-) 
I have already signed the CLA but it is still showing not signed...I have done the recheck several times as well...can you please help

**Comment by alfhenrik** [comment]
Hey @kazizahir,

No problem, we've had some issues with the CLA bot we use in that it doesn't always register that a user has signed the CLA and updates itself on GitHub.

I'll review and merge you changes as soon as I can.

Thank you for your contribution!

Cheers,
Henrik

**Comment by kazizahir** [comment]
Thanks @alfhenrik  for the fast response...I appreciate it :-)

**Comment by kazizahir** [comment]
Thanks @alfhenrik for taking the time and effort to review and merge in my contribution...I really appreciate it...I am feeling as happy as the guy in the above pic...thanks again :-)

**Pull request merged**
