### PR TITLE
Create azure-blob-storage-set-cors

### PR DESCRIPTION
**Pull request by jonsamwell**
Added a step template to set a CORS rule on a specified Azure storage blob container

### CODE REVIEW

**Comment by alfhenrik** [comment]
@jonsamwell thanks for your contribution!

One minor thing, could you change the storage account key to be a `Sensitive` control so it masks the key in the UI.

Thanks!

**Comment by jonsamwell** [comment]
@alfhenrik Done.  Thanks for reviewing this so quickly.

**Comment by alfhenrik** [comment]
Thanks @jonsamwell this has been pushed to production now.

**Comment by jonsamwell** [comment]
@alfhenrik Great stuff!

**Pull request merged**
