### PR TITLE
Fixing version search

### PR DESCRIPTION
**Pull request by twerthi**
---

# Background

Dynamic download functionality was failing due to author changing GitHub Asset file name.  Updated code to support both previous and updated file names.

# Results

Dynamic download will now function correctly.

## Before

Code would search for naming convention author of `grate` would use in previous versions.  Author updated file name convention causing code to fail to find the version to download.

## After

Code will now first try previous file name convention before checking for nuget package for cross-platform version of `grate`

# Pre-requisites

- [X] `Id` should be a **GUID** that is not `00000000-0000-0000-0000-000000000000`
  - **NOTE** If you are modifying an existing step template, please make sure that you **do not** modify the `Id` property *(updating the `Id` will break the Library sync functionality in Octopus)*. 
- [X] `Version` should be incremented, otherwise the integration with Octopus won't update the step template correctly
- [X] Parameter names should not start with `$`
- [X] **Step template parameter names (the ones declared in the JSON, not the script body) should be prefixed with a namespace so that they are less likely to clash with other user-defined variables in Octopus** (see [this issue](https://github.com/OctopusDeploy/Issues/issues/2126)). For example, use an abbreviated name of the step template or the category of the step template).
- [X] `LastModifiedBy` field must be present, and (_optionally_) updated with the correct author
- [ ] If a new `Category` has been created:
   - [ ] An image with the name `{categoryname}.png` must be present under the `step-templates/logos` folder
   - [ ] The `switch` in the `humanize` function in [`gulpfile.babel.js`](https://github.com/OctopusDeploy/Library/blob/master/gulpfile.babel.js#L92) must have a `case` statement corresponding to it

### CODE REVIEW

**Comment by mcasperson** [comment]
It is not related to this PR, but a suggestion is to replace

```
$tags = ($tags | Where-Object { $_.name.EndsWith($Version) })
```

with 

```
$tags = ($tags | Where-Object { $_.tag_name.EndsWith($Version) })
```

This is the JSON of the latest release:

```
{
    "url": "https://api.github.com/repos/erikbra/grate/releases/121944025",
    "assets_url": "https://api.github.com/repos/erikbra/grate/releases/121944025/assets",
    "upload_url": "https://uploads.github.com/repos/erikbra/grate/releases/121944025/assets{?name,label}",
    "html_url": "https://github.com/erikbra/grate/releases/tag/1.5.3",
    "id": 121944025,
    "author": {
      "login": "erikbra",
      "id": 1628994,
      "node_id": "MDQ6VXNlcjE2Mjg5OTQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1628994?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/erikbra",
      "html_url": "https://github.com/erikbra",
      "followers_url": "https://api.github.com/users/erikbra/followers",
      "following_url": "https://api.github.com/users/erikbra/following{/other_user}",
      "gists_url": "https://api.github.com/users/erikbra/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/erikbra/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/erikbra/subscriptions",
      "organizations_url": "https://api.github.com/users/erikbra/orgs",
      "repos_url": "https://api.github.com/users/erikbra/repos",
      "events_url": "https://api.github.com/users/erikbra/events{/privacy}",
      "received_events_url": "https://api.github.com/users/erikbra/received_events",
      "type": "User",
      "site_admin": false
    },
    "node_id": "RE_kwDOFP1ae84HRLfZ",
    "tag_name": "1.5.3",
    "target_commitish": "main",
    "name": "1.5.3 - PostgreSQL fixes and .NET 8rc1",
    "draft": false,
    "prerelease": false,
    "created_at": "2023-09-20T21:19:26Z",
    "published_at": "2023-09-20T21:32:14Z",
    ...
}
```

`tag_name` is the version, while `name` has some extra content (`1.5.3 - PostgreSQL fixes and .NET 8rc1`) which won't match the current logic.

**Review by mcasperson — CHANGES_REQUESTED** [review]
The tool author has also changed their release naming convention, which will break any checks requiring a fixed version, because the version checks are on the `name` fields rather than the `tag_name` field.

**Review by mcasperson — APPROVED** [review]
This is approved with one suggestion

**Comment by twerthi** [comment]
Good shout @mcasperson , thanks for spotting that!  I've updated a description of an input (copy-paste error from the template it replaced) as well as updated the search logic as it made a bad assumption.

**Comment by mcasperson** [comment]
It would be worth adding a check if `minorVersion` becomes negative. Without this check I assume the version parsing will fail on the next attempt (i.e. `1.2.-1` won't parse), which will probably throw a unhelpful error.

```
if ($null -eq $tags)
 {
 	# decrement minor version
       $minorVersion = [int]$parsedVersion.Minor
       $minorVersion --

       if ($minorVersion -ge 0) {
           # return the URLs
           return (Get-LatestVersionDownloadUrl -Repository $Repository -Version "$($parsedVersion.Major).$($minorVersion)")
       }
 }
```

**Comment by twerthi** [comment]
Implemented suggestion as well as an else condition to throw an error in the event that a negative number was found.

**Pull request merged**
