### PR TITLE
Adds a step template for OpsLevel deploy event tracking

### PR DESCRIPTION
**Pull request by rocktavious**
Includes the OpsLevel logo as well as 2 step templates (1 in bash and 1 in powershell) that perform the same action which is emit a payload to OpsLevel for tracking deploy events.  Step template requires installation of our [CLI](https://github.com/OpsLevel/cli) as a package.

### CODE REVIEW

**Review by ddorosz — APPROVED** [review]

**Review by BobJWalker — APPROVED** [review]

**Comment by rocktavious** [comment]
Hey @BobJWalker thanks for merging - Can you provide some advice on why i'm seeing the following after installing the community step and using it in a project?

Screen Shot 2021-07-30 at 2 10 20 PM
 
I have a feeling this effectively breaks the step since it cannot get the CLI properly installed via Octopus Deploy packages.  Is there any recommendation here on how to fix this or the best way to go about depending on an external CLI?

**Comment by BobJWalker** [comment]
Because I missed that you didn't have any packages in the packages object.  🤦 

How it should work:

1. I have a package parameter:
image

2. On the script screen add a package reference
image

3. Set the values to match something similar:
image

It _should_ extract it to the folder you specified in the scripts.  To be 100% certain you'll want to reference in a variable like so:  `Octopus.Action.Package[FlywayPackage].ExtractedPath`

You can see an example here: https://library.octopus.com/step-templates/ccebac39-79a8-4ab4-b55f-19ea570d9ebc/actiontemplate-flyway-database-migrations

Alternatively, you can provide an docker container that can used as execution containers: https://octopus.com/docs/projects/steps/execution-containers-for-workers

https://octopus.com/blog/tips-building-custom-execution-containers

**Comment by rocktavious** [comment]
@BobJWalker - Like this?  https://github.com/OctopusDeploy/Library/pull/1150

**Pull request merged**
