### PR TITLE
Updated to support PagerDuty API v2

### PR DESCRIPTION
**Pull request by tfbryan**
---

### Step template checklist

- [ ] `Id` should be a **GUID** that is not `00000000-0000-0000-0000-000000000000`
  - **NOTE** If you are modifying an existing step template, please make sure that you **do not** modify the `Id` property *(updating the `Id` will break the Library sync functionality in Octopus)*. 
- [ ] `Version` should be incremented, otherwise the integration with Octopus won't update the step template correctly
- [ ] Parameter names should not start with `$`
- [ ] **Step template parameter names (the ones declared in the JSON, not the script body) should be prefixed with a namespace so that they are less likely to clash with other user-defined variables in Octopus** (see [this issue](https://github.com/OctopusDeploy/Issues/issues/2126)). For example, use an abbreviated name of the step template or the category of the step template).
- [ ] `LastModifiedBy` field must be present, and (_optionally_) updated with the correct author
- [ ] If a new `Category` has been created:
   - [ ] An image with the name `{categoryname}.png` must be present under the `step-templates/logos` folder
   - [ ] The `switch` in the `humanize` function in [`gulpfile.babel.js`](https://github.com/OctopusDeploy/Library/blob/master/gulpfile.babel.js#L92) must have a `case` statement corresponding to it

### CODE REVIEW

**Comment by tfbryan** [comment]
@OctopusBob I thought I did sign the CLA and I even went and linked it. I'm not sure what is missing at this point.

**Comment by OctopusBob** [comment]
Hmmm, that's odd, did you sign in with a different GH account to accept the CLA than what was used to submit this PR?

**Comment by tfbryan** [comment]
> Hmmm, that's odd, did you sign in with a different GH account to accept the CLA than what was used to submit this PR?

Nope, I only have 1 account

**Comment by OctopusBob** [comment]
Hmm, I've gone over a few different items, everything looks to be correct.  Have you tried re-signing the CLA?  Or didn't that work either?

**Comment by tfbryan** [comment]
> Hmm, I've gone over a few different items, everything looks to be correct. Have you tried re-signing the CLA? Or didn't that work either?

When I access it, it shows all the options filled out and grey'd out. I don't see anything to do. Should we cancel and try again?

**Comment by OctopusBob** [comment]
I'm willing to try that.  I'll close this PR and you can create a new one.

**Pull request closed without merging**
