### PR TITLE
Added a line to support the new TLS requirements by the New Relic API

### PR DESCRIPTION
**Pull request by justin-newman**
The New Relic API now requires TLS 1.2 or above. I have added a line to this script to update the Security Protocol to Tls12 as advised by Shawn Sesna via the Octopus Deploy Slack channel.
https://octopususergroup.slack.com/archives/C6UGLUWMQ/p1579016095060000?thread_ts=1579015576.059200&cid=C6UGLUWMQ
Here is a link to the New Relic Documentation discussing the new requirements.
https://discuss.newrelic.com/t/january-tls-updates-apis-and-browser-apm/88869

### CODE REVIEW

**Comment by justin-newman** [comment]
I don't see anything requesting me to sign the CLA. It just says that it is required and Expected, but there is no link or button.

**Comment by justin-newman** [comment]
On top of that. If I go to https://cla-assistant.io/OctopusDeploy/library or https://cla-assistant.io/OctopusDeploy it says that I have already signed it.

**Comment by justin-newman** [comment]
maybe this? https://github.com/cla-assistant/cla-assistant/issues/520

**Comment by justin-newman** [comment]
I thought you would need to do something but my buddy hit a link from that bug and it restarted the check. Now it's green.

**Comment by tothegills** [comment]
Thank you @justin-newman !

**Comment by olsh** [comment]
The `version` property should be updated as well.

**Comment by tothegills** [comment]
Thanks @olsh, I missed that on the review. The version was bumped in this PR: https://github.com/OctopusDeploy/Library/pull/850

**Pull request merged**
