### PR TITLE
Creating F5 enable/disable multiple pools step template.

### PR DESCRIPTION
**Pull request by tbrasch**
Not sure why the other files were detected to have changed. Only trying to add f5-enable-disable-multiple-pools.json file is what I am trying to add.

### CODE REVIEW

**Comment by tbrasch** [comment]
Sorry for the mess with closing/reopening the pull request, and the extra files in the commit/pull request. First time going through this.

**Comment by alfhenrik** [comment]
Hi @tbrasch, 

No problem at all! Give me a shout if there is anything I can help with.

Cheers,
Henrik

**Comment by tbrasch** [comment]
Hi @alfhenrik, is there anything else I need to do?

**Comment by alfhenrik** [comment]
Hey @tbrasch,

Sorry I've not been able to get to your PR yet, I will try to get to it today or tomorrow.

Thanks,
Henrik

**Comment by tbrasch** [comment]
@alfhenrik absolute no worries!!! I was worried I needed to do something yet :)

**Comment by alfhenrik** [comment]
@tbrasch looks like there was some sort of white-space changes causing the unrelated files in your PR, not sure why and I couldn't actually determine what the changes were using any of my text compare tools. (I fixed it by resetting the unrelated files to the version in `master` before merging your PR into `master`).

Thank you very much for your contribution!

**Comment by tbrasch** [comment]
@alfhenrik Thanks for the help! I was learning how to do this as I was going along. I should have a cleaner Pull Request next time :)

Thanks again!!!

**Pull request merged**
