### PR TITLE
fix issuer list of LE's staging environment as per https://letsencrypt.org/docs/staging-environment/#intermediate-certificates

### PR DESCRIPTION
**Pull request by thomasdc**
### Step template checklist

- [x] `Id` should be a **GUID** that is not `00000000-0000-0000-0000-000000000000`
  - **NOTE** If you are modifying an existing step template, please make sure that you **do not** modify the `Id` property *(updating the `Id` will break the Library sync functionality in Octopus)*. 
- [x] `Version` should be incremented, otherwise the integration with Octopus won't update the step template correctly
- [x] Parameter names should not start with `$`
- [x] **Step template parameter names (the ones declared in the JSON, not the script body) should be prefixed with a namespace so that they are less likely to clash with other user-defined variables in Octopus** (see [this issue](https://github.com/OctopusDeploy/Issues/issues/2126)). For example, use an abbreviated name of the step template or the category of the step template).
- [x] `LastModifiedBy` field must be present, and (_optionally_) updated with the correct author
- [x] If a new `Category` has been created:
   - [ ] An image with the name `{categoryname}.png` must be present under the `step-templates/logos` folder
   - [ ] The `switch` in the `humanize` function in [`gulpfile.babel.js`](https://github.com/OctopusDeploy/Library/blob/master/gulpfile.babel.js#L92) must have a `case` statement corresponding to it

### CODE REVIEW

**Comment by harrisonmeister** [comment]
Hey @thomasdc 

Thanks for the update to the step templates.

I noticed you've removed the `Fake LE Intermediate X1` authority from the array completely.

Whilst unlikely for people to store test certs in a large number, the code checks for the existence of any one of the authorities when checking the Octopus Cert store for a matching cert. By removing `Fake LE Intermediate X1` you reduce the chances of a match. Realistically this will only affect certs for a max of 90 days, but I'm wondering if it still might be better to include the `Fake LE Intermediate X1` in the array.

What do you think?

**Review by harrisonmeister — APPROVED** [review]
LGTM, thanks!

**Comment by thomasdc** [comment]
@harrisonmeister Thanks for the review.

On another note, would it be interesting/feasible to extend the template so that it supports multiple domains as part of a SAN order? See [this](https://poshac.me/docs/v4/Functions/New-PAOrder/#example-2-multi-domain-with-plugin) documentation.

**Comment by harrisonmeister** [comment]
> @harrisonmeister Thanks for the review.
> 
> On another note, would it be interesting/feasible to extend the template so that it supports multiple domains as part of a SAN order? See [this](https://poshac.me/docs/v4/Functions/New-PAOrder/#example-2-multi-domain-with-plugin) documentation.

Hi @thomasdc - I think that would be a good addition. The only thing to take into account is the existing check that's done for a wildcard cert, e.g. the `Create Wildcard SAN` parameter as that adds an additional domain of `domain.com`.

The easiest way would be to support the existing parameter `Certificate Domain` to take a comma-separated list of items (noting the above parameter). We try to keep parameter changes to a minimum so since it already of type `SingleLineText`, changing into `MultiLineText` might cause people conversion problems (although I haven't tested that) :smile:

**Pull request merged**
