### PR TITLE
Add links back to product page in template descriptions

### PR DESCRIPTION
**Pull request by johnmwalley**

### CODE REVIEW

**Comment by tugberkugurlu** [comment]
Hmm, wondering when the awesome @DamianMac will merge this in :smile: :trollface:

**Comment by alfhenrik** [comment]
Merged, it will make it's way on to the Internetz in the near future.

**Comment by alfhenrik** [comment]
Promoted to Production

**Comment by tugberkugurlu** [comment]
Sweet, thanks @alfhenrik!

**Pull request merged**
