### PR TITLE
Added the "Seq - Log Deployment" step template

### PR DESCRIPTION
**Pull request by nblumhardt**
Hello!

This template allows the result of a deployment - success or failure - to be logged to a [Seq](https://getseq.net) log server.

image

This makes it possible to quickly correlate deployment events with other things going on in an environment - events/errors/etc.

### CODE REVIEW

**Comment by vanessalove** [comment]
Dunno if we can trust this one - might need to triple check the code ;)

**Comment by alfhenrik** [comment]
Don't worry, I'll be going over it with my super-fine comb :P

-----Original Message-----

**Comment by nblumhardt** [comment]
Gah! Detected! ;-)

**Comment by alfhenrik** [comment]
Thanks @nblumhardt this has been pushed to production now!

**Comment by nblumhardt** [comment]
:+1: thanks guys :)

**Pull request merged**
