### PR TITLE
Added step to notify deployment info to rabbitmq.

### PR DESCRIPTION
**Pull request by andreamaruccia**
This is the first step if you wish to create a ELK server to have some insight of your deployments.
http://www.eltuko.net/keep-track-of-octopus-deploys-with-the-elk-stack/

### CODE REVIEW

**Comment by alfhenrik** [comment]
Thanks very much for your contribution!

This will be pushed to production in the very near future.

**Comment by andreamaruccia** [comment]
no problem you're welcome!

**Comment by RobertoFlores** [comment]
@andreamaruccia do you know if they have a plan to push this pull request into production?

**Comment by matt-richardson** [comment]
This was released around that time - see https://library.octopusdeploy.com/step-templates/309f8497-7f79-4979-89a6-5d7e15d83ae2/actiontemplate-rabbitmq-notify-deploy

**Pull request merged**
